apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "killbill.fullname" . }}
  labels:
    {{- include "killbill.labels" . | nindent 4 }}
    tier: server
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "killbill.selectorLabels" . | nindent 6 }}
      tier: server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "killbill.selectorLabels" . | nindent 8 }}
        tier: server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{/*      serviceAccountName: {{ include "killbill.serviceAccountName" . }}*/}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: download-schema
          image: busybox
          command:
            - /bin/sh
            - "-c"
            - |
              echo 'CREATE DATABASE IF NOT EXISTS `killbill`;' >> /schema/killbill-ddl.sql
              echo 'USE killbill;' >> /schema/killbill-ddl.sql
              echo 'CREATE DATABASE IF NOT EXISTS `kaui`;' >> /schema/kaui-ddl.sql
              echo 'USE kaui;' >> /schema/kaui-ddl.sql
              wget http://docs.killbill.io/{{ .Values.killbill.version }}/ddl.sql -O - >> /schema/killbill-ddl.sql
              wget https://raw.githubusercontent.com/killbill/killbill-admin-ui/master/db/ddl.sql -O - >> /schema/kaui-ddl.sql
              wget https://raw.githubusercontent.com/killbill/killbill-stripe-plugin/master/src/main/resources/ddl.sql -O - >> /schema/killbill-ddl.sql
              wget https://raw.githubusercontent.com/killbill/killbill-analytics-plugin/master/src/main/resources/org/killbill/billing/plugin/analytics/ddl.sql - >> /schema/killbill-ddl.sql
              wget https://raw.githubusercontent.com/killbill/killbill-adyen-plugin/master/src/main/resources/ddl.sql -O - >> /schema/killbill-ddl.sql
              echo "INSERT INTO kaui.kaui_allowed_users (kb_username, description, created_at, updated_at) values ('admin', 'super admin', NOW(), NOW());" >> /schema/kaui-ddl.sql
              echo 'DONE!'
          volumeMounts:
            - mountPath: /schema
              name: schema
        - name: load-schema
          image: mysql:8.0.27
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "killbill.databaseSecretName" . }}
                  key: mysql-root-password
          command:
            - /bin/sh
            - "-c"
            - |
              mysql -u root -p$MYSQL_ROOT_PASSWORD -h {{ include "killbill.databaseHost" . }}  < /schema/killbill-ddl.sql
              mysql -u root -p$MYSQL_ROOT_PASSWORD -h {{ include "killbill.databaseHost" . }}  < /schema/kaui-ddl.sql
          volumeMounts:
            - mountPath: /schema
              name: schema
      volumes:
        - name: schema
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.killbill.image.repository }}:{{ .Values.killbill.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.killbill.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KILLBILL_DAO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: "mysql-root-password"
                  name: {{ include "killbill.databaseSecretName" . }}
            - name: KILLBILL_DAO_URL
              value: {{ include "killbill.databaseUrl" . | quote }}
            - name: KILLBILL_DAO_USER
              value: "root"
          resources:
          {{- toYaml .Values.killbill.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.killbill.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.killbill.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kaui.fullname" . }}
  labels:
    {{- include "kaui.labels" . | nindent 4 }}
    tier: server
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kaui.selectorLabels" . | nindent 6 }}
      tier: server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kaui.selectorLabels" . | nindent 8 }}
        tier: server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{/*      serviceAccountName: {{ include "killbill.serviceAccountName" . }}*/}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "kaui.fullname" . }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.kaui.image.repository }}:{{ .Values.kaui.image.tag }}"
          imagePullPolicy: {{ .Values.kaui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KAUI_CONFIG_DAO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: "mysql-root-password"
                  name: {{ include "killbill.databaseSecretName" . }}
            - name: KAUI_CONFIG_DAO_URL
              value: {{ include "killbill.databaseUrl" . | quote }}
            - name: KAUI_CONFIG_DAO_USER
              value: "root"
            - name: KAUI_KILLBILL_URL
              value: {{ include "killbill.url" . }}
          resources:
            {{- toYaml .Values.killbill.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.killbill.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.killbill.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
