{{- if and .Values.killbill.plugins.persistentVolume.enabled (not .Values.killbill.plugins.persistentVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "killbill.fullname" . }}-plugins
  labels:
    {{- include "killbill.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.killbill.plugins.persistentVolume.storage | default "1Gi" }}
{{- end }}