{{- if (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.databaseSecretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.auth.rootPassword) }}
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and (not (empty .Values.auth.username)) (not (empty .Values.auth.password)) }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}