# Default values for onedev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

onedev:
  image:
    repository: 1dev/server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
 
  nameOverride: ""
  fullnameOverride: ""
   
  nodeSelector: 
    kubernetes.io/os: linux

  persistentVolume:
    enabled: false
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: ""
    ## Size of a persistent volume to use
    storage: 10Gi
    
  emptyDir:
    ## Max size of a volume to use
    sizeLimit: ""

  maintenance: false

  service:
    annotations: {}
    type: LoadBalancer
    httpPort: 80
    sshPort: 22

  resources: { }
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
  #   memory: 128Mi

mysql:
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "8.0"
  
  enabled: true
  
  auth:
    database: "onedev"
    ## Name of the existing secret storing root password of MySQL database
    existingSecret: ""
    
  nodeSelector: 
    kubernetes.io/os: linux
    
  persistentVolume:
    enabled: false
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: ""
    ## Size of a persistent volume to use
    storage: 5Gi
    
  emptyDir:
    ## Max size of a volume to use
    sizeLimit: ""    

  service:
    type: ClusterIP
    port: 3306
    
  ## Configuration of backup to secondary PV
  backupVolume:
    enabled: false
    ## Cron job schedule
    schedule: ""
    persistentVolume:
      enabled: false
      ## If defined, PVC must be created manually before volume will be bound
      existingClaim: ""
      ## Size of a persistent volume to use
      storage: 5Gi
  
  backupS3:
    enabled: false
    ## Cron job schedule
    schedule: ""
    ## Name of the secret storing details of accessing S3 storage
    existingSecret: ""
    
imagePullSecrets: []

certmanager:
  enabled: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

initContainers: []
      
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: demo.onedev.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  ## Name of the SSL certificate provider to use from:
  ## - self-signed
  ## - letsencrypt
  sslProvider: "self-signed"
  certificateIssuer: ""
  tls: 
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  acme:
  #  email: "user@example.com"
  #  server: "https://acme-staging-v02.api.letsencrypt.org/directory"


