apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "janus.fullname" . }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "janus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "janus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "janus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8188
              protocol: TCP
          volumeMounts:
            - name: janus-config
              mountPath: /usr/local/etc/janus/janus.jcfg
              subPath: janus.jcfg
            - name: janus-config
              mountPath: /usr/local/etc/janus/janus.plugin.videoroom.jcfg
              subPath: janus.plugin.videoroom.jcfg
            - name: janus-config
              mountPath: /usr/local/etc/janus/janus.transport.http.jcfg
              subPath: janus.transport.http.jcfg
            - name: janus-config
              mountPath: /usr/local/etc/janus/janus.transport.websockets.jcfg
              subPath: janus.transport.websockets.jcfg
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: janus-config
          configMap:
            name: {{ include "janus.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
