kind: ConfigMap
metadata:
  name: {{ include "james.fullname" . }}-config-props
apiVersion: v1
data:
  james-database.properties: |-
    database.driverClassName=com.mysql.cj.jdbc.Driver
    database.url=jdbc:mysql://{{ include "james.databaseHost" . }}/{{ include "james.databaseName" . }}?allowPublicKeyRetrieval=true
    database.username={{ include "james.databaseUsername" . }}
    database.password={{ include "james.databasePassword" . }}

    openjpa.streaming=false

---

kind: ConfigMap
metadata:
  name: {{ include "james.fullname" . }}-tigase-rest-client-xml
apiVersion: v1
data:
  tigaserestclient.xml: |-
    <?xml version="1.0"?>
    <tigaserestclient>
        <tigaseHttpApiUrl>http://{{ include "james.tigaseHost" . }}:{{ include "james.tigasePort" . }}</tigaseHttpApiUrl>
        <tigaseAdminUsername>{{ include "james.tigaseAdminUsername" . }}</tigaseAdminUsername>
        <tigaseAdminPassword>{{ include "james.tigaseAdminPassword" . }}</tigaseAdminPassword>
        <tigaseUseCache>true</tigaseUseCache>
        <tigaseExpirationTimeInMinutes>1</tigaseExpirationTimeInMinutes>
    </tigaserestclient>


