apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "james.fullname" . }}
  labels:
    {{- include "james.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "james.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "james.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: download-jdbc-driver
          image: busybox
          command:
            - /bin/sh
            - "-c"
            - |
              if [ ! -f /root/libs/mysql-connector-java-8.0.30.jar ]; then
                echo "Downloading MySQL JDBC driver..."
                wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar -O - > /root/libs/mysql-connector-java-8.0.30.jar
              fi
          volumeMounts:
            - mountPath: /root/libs
              name: james-jdbc-driver
        - name: init-keystore
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - /bin/sh
            - "-c"
            - |
              if [ ! -f /root/conf/keystore ]; then
                echo "Generating keystore...";
                keytool -genkey -alias james -dname "CN=james" -keyalg RSA -storepass james72laBalle -keystore /root/conf/keystore
              fi
          volumeMounts:
            - mountPath: /root/conf
              name: james-config-data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: smtps
              containerPort: 465
              protocol: TCP
            - name: smtp-starttls
              containerPort: 587
              protocol: TCP
            - name: pop3
              containerPort: 110
              protocol: TCP
            - name: pop3s
              containerPort: 995
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP
            - name: imaps
              containerPort: 993
              protocol: TCP
            - name: http-admin
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: james-config-props
              mountPath: /root/conf/james-database.properties
              subPath: james-database.properties
            - name: james-config-data
              mountPath: /root/conf/keystore
              subPath: keystore
            - name: james-jdbc-driver
              mountPath: /root/libs/mysql-connector-java-8.0.30.jar
              subPath: mysql-connector-java-8.0.30.jar
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: james-config-props
          configMap:
            name: {{ include "james.fullname" . }}-config-props
        - name: james-config-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "james.fullname" . }}-config-data
          {{- else }}
          emptyDir:
            {}
          {{- end }}
        - name: james-jdbc-driver
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "james.fullname" . }}-jdbc-driver
          {{- else }}
          emptyDir:
            {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
