apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "james.fullname" . }}
  labels:
    {{- include "james.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "james.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "james.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: smtps
              containerPort: 465
              protocol: TCP
            - name: smtp-starttls
              containerPort: 587
              protocol: TCP
            - name: pop3
              containerPort: 110
              protocol: TCP
            - name: pop3s
              containerPort: 995
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP
            - name: imaps
              containerPort: 993
              protocol: TCP
            - name: http-admin
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: james-config-props
              mountPath: /root/conf/james-database.properties
              subPath: james-database.properties
            - name: james-config-data
              mountPath: /root/secrets/keystore
              subPath: keystore
            - name: james-tigase-rest-client-xml
              mountPath: /root/conf/tigaserestclient.xml
              subPath: tigaserestclient.xml
            - name: james-james-mailetcontainer-xml
              mountPath: /root/conf/mailetcontainer.xml
              subPath: mailetcontainer.xml
            {{- if .Values.ingress.tls.secretName }}
            - name: james-secrets
              mountPath: /root/secrets
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: james-config-props
          configMap:
            name: {{ include "james.fullname" . }}-config-props
        - name: james-tigase-rest-client-xml
          configMap:
            name: {{ include "james.fullname" . }}-tigase-rest-client-xml
        - name: james-james-mailetcontainer-xml
          configMap:
            name: {{ include "james.fullname" . }}-james-mailetcontainer-xml
        - name: james-config-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "james.fullname" . }}-config-data
          {{- else }}
          emptyDir:
            {}
          {{- end }}
        - name: james-secrets
          projected:
            sources:
              - secret:
                  name: {{ include "james.fullname" . }}
                  items:
                    - key: tls.key
                      path: tls.key
                    - key: tls.crt
                      path: tls.crt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
