{{- if and .Values.auth.username .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "james.fullname" . }}-auth
  labels:
    {{- include "james.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ htpasswd .Values.auth.username .Values.auth.password | b64enc | quote }}
{{- end }}