apiVersion: v1
kind: Service
metadata:
  name: {{ include "onedev.fullname" . }}
  labels:
    {{- include "onedev.labels" . | nindent 4 }}
    tier: server
spec:
  type: {{ .Values.onedev.service.type }}
  ports:
    - port: {{ .Values.onedev.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.onedev.service.sshPort }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "onedev.selectorLabels" . | nindent 4 }}
    tier: server
---
{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "onedev.labels" . | nindent 4 }}
    tier: database
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "onedev.selectorLabels" . | nindent 4 }}
    tier: database
{{- end }}