apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coturn.fullname" . }}-config
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
data:
  turnserver.conf: |
    use-auth-secret
    realm={{ .Values.vhost }}
    min-port={{ .Values.ports.from }}
    max-port={{ .Values.ports.to }}
    log-file=stdout
    pidfile=/var/tmp/turnserver.pid
    userdb=/var/tmp/turnserver.db
    no-cli
    no-tls
    no-dtls
    prod
    no-tcp-relay