{{- if and .Values.secret.password .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.password }}
{{- end }}