{{- if .Values.service.enabled }}
{{- $portRange := untilStep (int .Values.ports.from) (int .Values.ports.to) 1 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3478
      targetPort: turn-3478
      protocol: UDP
      name: turn-3478
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 3478
      {{- end }}
    {{- range $portRange }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: turn-{{ . }}
      {{- if eq $.Values.service.type "NodePort" }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}      
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
{{- end }}