{{- $sslCertificateIssuer := .Values.ingress.sslCertificateIssuer | default (printf "%s-cluster-issuer" (include "tigase-xmpp-server.fullname" .)) | trunc 63 | trimSuffix "-" -}}
{{- $subdomains := .Values.certificate.subdomains -}}
{{- $root := . -}}
{{- range $domain := .Values.certificate.domains }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $domain }}
  labels:
    {{- include "tigase-xmpp-server.labels" $root | nindent 4 }}
spec:
  secretName: {{ $domain }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ $sslCertificateIssuer }}
  commonName: {{ $domain }}
  dnsNames:
    - {{ $domain }}
    {{- range $subdomain := $subdomains }}
    - {{ $subdomain }}.{{ $domain }}
    {{- end }}
{{- end }}