apiVersion: v1  
kind: Service
metadata:
  name: {{ include "tigase-xmpp-server.fullname" . }}
  labels:
    {{- include "tigase-xmpp-server.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies:
    {{- range $ipFamily := .Values.service.ipFamilies }}
    - {{ $ipFamily }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.http }}
      {{- end }}
    - port: {{ .Values.service.ports.bosh }}
      targetPort: xmpp-bosh
      protocol: TCP
      name: xmpp-bosh
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.bosh }}
      {{- end }}
    - port: {{ .Values.service.ports.c2s }}
      targetPort: xmpp-c2s
      protocol: TCP
      name: xmpp-c2s
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.c2s }}
      {{- end }}
    - port: {{ .Values.service.ports.cs2s }}
      targetPort: xmpp-cs2s
      protocol: TCP
      name: xmpp-cs2s
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.cs2s }}
      {{- end }}
    - port: {{ .Values.service.ports.ws2s }}
      targetPort: xmpp-ws2s
      protocol: TCP
      name: xmpp-ws2s
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.ws2s }}
      {{- end }}
    - port: {{ .Values.service.ports.wss2s }}
      targetPort: xmpp-wss2s
      protocol: TCP
      name: xmpp-wss2s
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.wss2s }}
      {{- end }}
    - port: {{ .Values.service.ports.s2s }}
      targetPort: xmpp-s2s
      protocol: TCP
      name: xmpp-s2s
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.s2s }}
      {{- end }}
    {{- if .Values.ldap.enabled }}
    {{- if and .Values.ldap.plain.enabled  .Values.service.ports.ldap }}
    - port: 10389
      targetPort: ldap
      protocol: TCP
      name: ldap
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.ldap }}
      {{- end }}
    {{- end }}
    {{- if and .Values.ldap.ssl.enabled  .Values.service.ports.ldaps }}
    - port: 10636
      targetPort: ldaps
      protocol: TCP
      name: ldaps
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.ldaps }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "tigase-xmpp-server.selectorLabels" . | nindent 4 }}
---
{{- if and .Values.ldap.enabled (or .Values.ldap.plain.enabled .Values.ldap.ssl.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tigase-xmpp-server.ldap.fullname" . }}
  labels:
    {{- include "tigase-xmpp-server.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.ldap.plain.enabled }}
    - port: 10389
      targetPort: ldap
      protocol: TCP
      name: ldap
    {{- end }}
    {{- if .Values.ldap.ssl.enabled }}
    - port: 10636
      targetPort: ldaps
      protocol: TCP
      name: ldaps
    {{- end }}
  selector:
    {{- include "tigase-xmpp-server.selectorLabels" . | nindent 4 }}
{{- end }}